### PR TITLE
Add --cpu-rt-runtime to allow Docker allocate real-time CPU time (#1235)

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Review by pvizeli — APPROVED** [review]

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervisor/pull/2593

**Comment by jens-maus** [comment]
This refs https://github.com/home-assistant/operating-system/issues/1235

**Comment by jens-maus** [comment]
I tested the changes suggested by this PR in HAos and I could reproduce that at least docker has now enough `cpu.rt_runtime_us` resources assigned:

```
# cat /sys/fs/cgroup/cpu/docker/cpu.rt_runtime_us
950000
```

However, the suggested change by @pvizeli in https://github.com/home-assistant/supervisor/pull/2593 seems not be enough to get each container started by docker enough real-time shares so that applications using `sched_setscheduler()` are able to run correctly. So even after using a supervisor developer build with the changes by  https://github.com/home-assistant/supervisor/pull/2593 and the new `realtime` option used in `config.json` of the add-on ends up in ...

```
/ # cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us
0
/ # multimacd -l 0 -c
[...]
2021/02/21 18:55:42.923 <Warning> Could not set scheduling priority: Operation not permitted
2021/02/21 18:55:42.923 <Warning> Could not set scheduling priority: Operation not permitted
2021/02/21 18:55:42.923 <Warning> Could not set scheduling priority: Operation not permitted
``` 

Reviewing the changes suggested by https://github.com/home-assistant/supervisor/pull/2593 it looks like only the `--ulimit rtprio=99` option is added by the new `realtime` option when starting the docker container of add-ons. However, AFAIK the `--cpu-rt-runtime=950000` option is also required to get the `cpu.rt_runtime_us` cgroup raised accordingly.

See https://docs.docker.com/config/containers/resource_constraints/#configure-the-realtime-scheduler

**Comment by pvizeli** [comment]
https://github.com/home-assistant/supervisor/pull/2602

Need also an `SUPERVISOR_CPU_RT=1` on the env @agners

**Review by pvizeli — CHANGES_REQUESTED** [review]
`SUPERVISOR_CPU_RT=1` for supervisor startup

**Comment by jens-maus** [comment]
@agners @pvizeli

Sorry to bring this up here again, but I actually tried to check if the changes mentioned here (in HAos and the supervisor) actually work so that the new `realtime` option in an add-on actually brings up the container with enough real-time cpu time now. For this I installed my own dev version of HAos (from latest `dev` branch) with the changes from @agners and switched immediately to the beta channel so that supervisor 2021.02.12 was installed and is running. In fact, while I can see that `dockerd` is perfectly running with `--cpu-rt-runtime` and the new `SUPERVISOR_CPU_RT` env variable is propagated to the supervisor, my test add-on  container is still outputting the following

```
# cat /sys/fs/cgroup/cpu/cpu.rt_runtime_us
0
```

which suggests that the `cpu.rt_runtime_us` setup does not work as expected even thought I have `"realtime": true` defined in the `config.json` of the test add-on. So did someone from you actually test that the new combination of the HAos changes work nicely together with the new 2021.02.12 changes regarding real-time changes for add-ons.

**Pull request merged**
