### PR TITLE
Add rtw89, mt7921 and mt7922 WiFi and BT firmware

### PR DESCRIPTION
**Pull request by sairon**
Add new firmwares and enable them for all targets. Bloat in rootfs in my x86_64 test build was ~2.16 MiB.

Buildroot bump:

* buildroot 8a75878da4...4c89661fd1 (2):
  > package/linux-firmware: add WiFi and BT firmware for MT7921 and MT7922
  > package/linux-firmware: add rtw89 firmware files

### CODE REVIEW

**Review by agners — APPROVED** [review]

**Comment by ikhimichenko** [comment]
Thank you guys for fixing Bluetooth for raspberry 4 on this release

**Comment by sairon** [comment]
@ikhimichenko It's a bit off-topic in this PR, yet I have to ask - what issues you've had, and has 11.3 resolved them for you?

**Comment by ikhimichenko** [comment]
Yes, that was fixed in this particular release.
Two or three releases (updates for HA) before Bluetooth for my RP4 was broken with the following message  Failed setup, will retry.
So bluetooth integration constant state of initializing / retrying setup.
I’m a newbie in the HA so I’m sorry if my answer is not met you question.

**Comment by sairon** [comment]
@parisisal Thanks for the feedback, it turns out that enabling of `BR2_PACKAGE_LINUX_FIRMWARE_RTL_RTW89` option is missing in this PR :grimacing: The driver is there, just the FW is missing - so if you check `dmesg` there should be a message from the firmware loader the file couldn't be found. I'll create a PR to fix it, so it will indeed be available since 11.4. Sorry for the false hopes.

**Comment by parisisal** [comment]
Hi,
I just installed the 11.4 SO, but i still not see the wlan adapter.
I rebooted the machine.
Here the dmesg [dmesg.txt](https://github.com/home-assistant/operating-system/files/13886699/dmesg.txt)
Should I do somenthing in order to load correctly the driver?

**Comment by sairon** [comment]
@parisisal Sorry again - whole time I was checking for a wrong PCI identifier. It turns out that driver for 8852**BE** was only added to Linux 6.2+. 6.1.x only has 8852AE and 8852CE drivers. It's get lost easily in the jungle of all the device models :facepalm:
So far only BT works for that Realtek card (which is confirmed in the `dmesg` output you provided), WiFi will need a kernel update (which should be hopefully available Soon™).

**Comment by parisisal** [comment]
> @parisisal Sorry again - whole time I was checking for a wrong PCI identifier. It turns out that driver for 8852**BE** was only added to Linux 6.2+. 6.1.x only has 8852AE and 8852CE drivers. It's get lost easily in the jungle of all the device models 🤦 So far only BT works for that Realtek card (which is confirmed in the `dmesg` output you provided), WiFi will need a kernel update (which should be hopefully available Soon™).

Don't worry, first of all thank you for you work. Nice to help.

**Comment by ikhimichenko** [comment]
Again, after core update for Raspberry pi 4b - bluetooth doesn't work
image

**Pull request merged**
