### PR TITLE
use GPT partition table for rpi4

### PR DESCRIPTION
**Pull request by tmm1**
The RPI4 eeprom bootloader can read directly from GPT, so hybrid MBR is not necessary.

### CODE REVIEW

**Review by pvizeli — APPROVED** [review]

**Comment by pvizeli** [comment]
Can you add this also to rpi4-64?

**Comment by agners** [comment]
Actually, I tested that on 64-bit and it seems to break boot (I get the rainbow screen, no U-Boot on serial port).

**Comment by tmm1** [comment]
Hmm I have been using this with rpi64 and it was working okay.

Maybe it's related to the eeprom version? Or maybe it only works for USB drives.

**Comment by agners** [comment]
> Maybe it's related to the eeprom version? Or maybe it only works for USB drives.

EEPROM is the latest 2020-09-03. I tested using SD card, so that could be the difference...

**Comment by pvizeli** [comment]
> Or maybe it only works for USB drives.

Look like. However, the SD card is the focus for us, since booting from a hard disk with an SoC is maybe working but hacky at all.

**Comment by tmm1** [comment]
Hm I tried with SD and it also works. I must have done something wrong in this PR so I will check it again.

Can you share the `sgdisk -Op` from your generated image?

**Comment by agners** [comment]
> Can you share the sgdisk -Op from your generated image?

Cleared that SD already again, would have to recreate.

FWIW, its a RPi 8GB I tested it here. I just added `BOOT_SYS=efi`, and made sure boot partition and all really get rebuilt by doing a clean build.

**Comment by pvizeli** [comment]
> Actually, I tested that on 64-bit and it seems to break boot (I get the rainbow screen, no U-Boot on serial port).

So this doesn't work on the SD card, right?

**Comment by agners** [comment]
Retested this with the new firmware, and it seems to work well on a RPi4 8GB.

**Pull request merged**
