### PR TITLE
Updated to lastest generic_raw_uart version

### PR DESCRIPTION
**Pull request by alexreinert**

### CODE REVIEW

**Comment by agners** [comment]
Should this go into release 7 still? If so, I'll add a `REL-7` label and backport it before the next release candidate.

**Comment by alexreinert** [comment]
If there is no change freeze, this would be nice.

**Comment by jens-maus** [comment]
I can approve this PR and flag it REL-7 if this is fine with you @agners

**Comment by alexreinert** [comment]
It seems, that there is an issue on RPI3 boards. I will do some further investigations and provide a new PR, when I fixed it.

**Pull request closed without merging**
