### PR TITLE
Bump Raspberry Pis to 5.4 kernel

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Comment by agners** [comment]
So far I tested the 32-bit image on a Raspberry Pi 3 Model B+ and the 64-bit image on a Raspberry Pi 4 Model B 8GB.

**Review by pvizeli — APPROVED** [review]
Looks fine to me. Do the uart mapping working to GPIO?

**Comment by tmm1** [comment]
Tested on Pi4 2GB w/ USB boot and works fine. I will keep it on my dev unit to stress test more over the next few days.

Last time I was playing with 5.4 kernel, once after a reboot I had a problem with ethernet not coming up. I found a related issue which is worth tracking: https://github.com/raspberrypi/linux/issues/3108

**Comment by pvizeli** [comment]
I have the same issue sometimes with XU4

**Comment by agners** [comment]
> Looks fine to me. Do the uart mapping working to GPIO?

With the last update enabling UART2 through 5 works, with or without `enable_uart=1`.

**Comment by bschatzow** [comment]
I am having issues with the 64 bit kernel causing Home Assistant to freeze.  I see anywhere from a couple of hours to a couple of days maximum before I need to power off the Pi4 . Running on SSD drive.  Is there some details I can add to try and see what the issue is?  The system is very stable on all OS releases prior to OS5.5 when this change was implemented,

**Pull request merged**
