### PR TITLE
Add Ralink rt27xx/rt28xx/rt30xx firmware (#1242)

### PR DESCRIPTION
**Pull request by agners**
Add Ralink firmware for devices which have the driver enabled. The
firmwares are with a total of 20KiB rather small.

### CODE REVIEW

**Comment by pvizeli** [comment]
Why do we add a Wireless USB card to a board with wifi supported?

**Comment by agners** [comment]
I just added it everywhere where the drivers have been enabled. I feel an enabled driver warrants the firmwares to be present.

Alternatively we can disable the driver, but I think currently all RPis use the same kernel config.

**Comment by agners** [comment]
@pvizeli removed most WiFi drivers from Tinker Board, as drivers without firmware really are useless.

For Raspberry Pi, this is a bit more painfull as we use defconfig from the kernel tree. I just don't add the Ralink firmware where on-board WiFi is there.

**Review by pvizeli — COMMENTED** [review]
LGTM. It was just a question :) Do you want not to add this to odroid?

**Pull request merged**
