### PR TITLE
Remove rootfstype for Raspberry Pi 5

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Review by sairon — APPROVED** [review]

**Comment by cybernard** [comment]
Twice when I applied this update from within home assistant, home assistant on my Raspberry Pi 5 stopped booting with a kgdboc error message.  I had to restore from backup.

kgdboc: deferred probe pending

**Comment by Swwils** [comment]
This update broke my install on RasPi 5.

**Comment by invisible-ladka** [comment]
> Twice when I applied this update from within home assistant, home assistant on my Raspberry Pi 5 stopped booting with a kgdboc error message. I had to restore from backup.
> 
> kgdboc: deferred probe pending

same thing happed with me too and im totally new to ha idont know what to do now

**Comment by agners** [comment]
Yes, sorry about this, this will be resolved with #3085, so the next update should work fine.

To fix your installation, insert the SD card into your system. On the first FAT partition of the SD card, you'll find a file named `config.txt`. Open it using a text editor. There should be a line starting with `cmdline=`. It probably is set to `cmdline=/cmdline-tryboot.txt` currently.Change it to `cmdline=/cmdline.txt`. Save and close the file. Unmount (cleanly eject) the SD card, and insert it back into your Raspberry Pi 5. This should make it boot again.

**Comment by invisible-ladka** [comment]
> Yes, sorry about this, this will be resolved with #3085, so the next update should work fine.
> 
> To fix your installation, insert the SD card into your system. On the first FAT partition of the SD card, you'll find a file named `config.txt`. Open it using a text editor. There should be a line starting with `cmdline=`. It probably is set to `cmdline=/cmdline-tryboot.txt` currently.Change it to `cmdline=/cmdline.txt`. Save and close the file. Unmount (cleanly eject) the SD card, and insert it back into your Raspberry Pi 5. This should make it boot again.

im using  usb thumb drive and when i plug it in pc multiple drives shows up like 5-6.. and none of those are able to open

**Pull request merged**
