### PR TITLE
pc/ova: support virtio-fs

### PR DESCRIPTION
**Pull request by andrew-d**
This enables support for [virtio-fs](https://virtio-fs.gitlab.io/), a shared filesystem for virtual machines. This allows very low-overhead file sharing between the host and guest when running a VM. I want to use this for sharing media files from Home Assistant to the host, where other programs/VMs can access them.

I tested this by running `make ova` locally to confirm that the Linux kernel built properly, which it did.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @andrew-d, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1400).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Review by agners — APPROVED** [review]

**Comment by pvizeli** [comment]
Don't forget that it's need also https://github.com/home-assistant/supervisor/issues/2564 otherwise if you doing it manual, it still end trouble

**Comment by agners** [comment]
Yeah I was wondering that too: this is not a block device but a file system, so it doesn't work as root disk drive (like virtio disk). In other words, you have to explicitly mount such a file system. So this requires something like @pvizeli is mentioning.

That said, I don't think it hurts to enable the drive on OS side already to start experimenting/development etc.

**Comment by andrew-d** [comment]
Yeah, my plan was to start out with a test add-on, running privileged, that could mount a `virtio-fs` filesystem from the host and e.g. copy files to/from the VM. If that works out well, then integrating with the supervisor or something else would be a good next step.

**Comment by andrew-d** [comment]
@agners - I don't particularly mind when, but do you have a rough idea of when a version of HassOS will be released with these options? I need to do a VM migration at some point in the future, and if it'll be "soon", then I'll hold off; if not, I can do it now. Either is fine, so no pressure - just curious :smiley:

**Comment by agners** [comment]
Another release 6 version is on my todo, probably towards the end of this week.

**Comment by andrew-d** [comment]
> Another release 6 version is on my todo, probably towards the end of this week.

Thanks! Much appreciated :grinning:

**Comment by deviantintegral** [comment]
Glad to see this added - this should be perfect for saving video streams outside of a VM image. @andrew-d if you end up starting an addon for this, please link it as I'd be glad to test it out.

**Pull request merged**
