### PR TITLE
Let's use our online check file

### PR DESCRIPTION
**Pull request by pvizeli**

### CODE REVIEW

**Comment by pvizeli** [comment]
Should work but is not tested

**Comment by agners** [comment]
Hm, I see, this is required to make the NetworkManager connectivity check actually work. ArchLinux sets it in `/usr/lib/NetworkManager/conf.d/20-connectivity.conf`. I think we should also set it in `/usr/lib/NetworkManager/conf.d/` as this is a distribution wide setting...

**Comment by ludeeus** [comment]
Wherever this setting end up, we should also adjust the supervised-installer script to do the same, and cache that file hard in cloudflare

**Comment by pvizeli** [comment]
Do you want to split it from a single config into a multi config import on a read-only system? Your choice.

**Comment by agners** [comment]
@ludeeus 
> Wherever this setting end up, we should also adjust the supervised-installer script to do the same
Given that distributions already set something I am not sure we should do that. Supervised always feels to me we should leave the underlying OS largely alone.

> cache that file hard in cloudflare
Yep!

@pvizeli maybe actually move the whole thing to `/usr/lib`. While we have `/etc/NetworkManager/*` not writeable by users today, I like to have that option for the future maybe. You can overwrite settings made by the distribution in `/usr/lib/NetworkManager/` from `/etc/NetworkManager/`, which might come in handy later.

**Pull request closed without merging**
