### PR TITLE
Linux: Update kernel 5.15.40

### PR DESCRIPTION
**Pull request by gregkh**
Signed-off-by: Greg Kroah-Hartman <gregkh@linuxfoundation.org>

### CODE REVIEW

**Comment by gregkh** [comment]
No reason at all, I just figured you all wanted to do this in stages, one release at a time :)

I'll bump this to .40 if you think that's better.

**Comment by agners** [comment]
I usually bump the stable kernel before I do the next OS release, often build a dev release and do some real world testing before building the actual release.

> I'll bump this to .40 if you think that's better.

Yes please. OS 8.1 will likely be released soon.

**Comment by gregkh** [comment]
Now changed to .40

Want me to do this every week when I release these kernels to keep these devices up to date and secure?

**Comment by jens-maus** [comment]
> Want me to do this every week when I release these kernels to keep these devices up to date and secure?

You really have the time to do that and bump the kernel version of HAos here together with your linux core development responsibilities at https://github.com/torvalds/linux? ;-)

I am impressed and would definitly (+1) vote for it if you would regularly contribute to this project.

**Comment by gregkh** [comment]
I think you mean to point to https://git.kernel.org/pub/scm/linux/kernel/git/stable/linux.git/  kernel development doesn't happen on github :)

And yes, bumping the kernel version here wouldn't be that difficult, I'll try to remember now that I rely more on HA and want to see it succeed.

**Comment by jens-maus** [comment]
> And yes, bumping the kernel version here wouldn't be that difficult, I'll try to remember now that I rely more on HA and want to see it succeed.

Perfect. But we could also in theory think about adding a github workflow/dependency check that automatically generates kernel update PRs as soon as you have released a new kernel ;)

**Comment by agners** [comment]
Actually, there is a rudimentary script committed at `scripts/update-kernel-upstream.sh`. I guess wrapping that into a GH Action shouldn't be a big deal. What I am a bit worried is to have countless of "unnecessary"  bumps in the git history/change log (which don't get released).

Ideally it should be like Dependabot, where you can just leave the PR sitting there and you get it updated to the latest automatically. Then we can merge whenever we actually plan to release.

**Comment by gregkh** [comment]
"Bumps" are good, as they provide a way to bisect back in case of regressions.  Jumping large version numbers is always harder in the end if there is a problem.

Anyway, it's your call as to if you want an "update for every stable release" or "one update a week", or "one update a month" or something else. I just want to make sure my HA device is running the latest and most stable/secure kernel release there is at the moment.  Thanks!

**Comment by agners** [comment]
> "Bumps" are good, as they provide a way to bisect back in case of regressions. Jumping large version numbers is always harder in the end if there is a problem.

Yeah true, but then I sometimes trigger builds quite a bit apart, so there won't be any binaries. But then again, having the commits already in source can be helpful still. I guess a "clean change log" is kinda lame reason to not do the right thing: Make sure dev is pointing to the latest stable. :sweat_smile: 

Out of curiosity, what hardware are you running HAOS on?

**Pull request merged**
