### PR TITLE
Fix issue with Odroid-N2 on USB

### PR DESCRIPTION
**Pull request by pvizeli**

### CODE REVIEW

**Comment by pepeEL** [comment]
It is mean that we can run from USB HassOS on Odroid N2 ?

**Comment by bramkragten** [comment]
This is just a bug fix where USB devices could cause a crash.

**Comment by pepeEL** [comment]
OK.
But is any chance to add to operatin system option for Odroid N2 to boot from USB memory ?

**Comment by bramkragten** [comment]
Don't use (closed) PR's for questions/requests.

**Comment by pepeEL** [comment]
But where i can ask ?

**Comment by frenck** [comment]
<https://www.home-assistant.io/help>

**Pull request merged**
