### PR TITLE
Enable Microsoft HyperV integration services

### PR DESCRIPTION
**Pull request by agners**

### CODE REVIEW

**Comment by agners** [comment]
See also #2376 and #1996.

**Comment by scyto** [comment]
wow, thanks, would you like me to test this now in any sort of way or just wait for this change to get into beta and then test?

**Comment by agners** [comment]
Yes you can find dev builds here: https://os-builds.home-assistant.io/10.0.dev20230302/

You can also update an existing installation to this dev build using

```
ha su options --channel=dev
ha su reload
ha su update
ha os update
```

**Comment by scyto** [comment]
I downloaded the new VHDX to my hyperv-server and spun up a new VM rather than touching my live install

I can report that production level checkpoints work perfectly now, thanks for doing this - this now means my synology backup process backs this VM p like i need it to :-)

also for your reference i can confirm that hyper-v gues services is now functionally equivalent to the experience on native debian 11 install in that the following doesn't work in hyper-v MMC UI:

1. type clipboard text doesn't work
2. capture screen returns the following

image

**to be clear i am saying if someone files a bug complaining about these two behaviours it IS NOT home assistant specific** - hopefully that might spare you sometime later if anyone reports those, lol :-)

**Comment by agners** [comment]
Thanks for testing!

**Pull request merged**
