### PR TITLE
Enable k10temp kernel module

### PR DESCRIPTION
**Pull request by agners**
The k10temp module allows to monitor CPU temperature on AMD systems.

### CODE REVIEW

**Review by bearhntr — COMMENTED** [review]
When and How will I see this change?  Will it come out in a 2022.x.x release?

**Comment by agners** [comment]
OS releases are separate. This will be part of OS 9.0. Currently a development build is on its way. If you enable the development channel it should be part of `9.0.dev20220831`.

**Comment by bearhntr** [comment]
That is awesome - If there is anything I can test, please let me know.  I truly hope that fixes my CPU Temp issues.  

Greatly appreciate your help. 

Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by agners** [comment]
If you want, you can verify if CPU temp indeed works with this change. You can install the latest development build from https://os-builds.home-assistant.io/9.0.dev20220831/ or use the built-in update mechanism.

```
ha su options --channel dev
ha su reload
ha os update
```

Switch back to stable channel afterwards

```
ha su options --channel beta
ha su reload
```

**Comment by bearhntr** [comment]
Stefan,

Tried the commands you gave - and I got this:



Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by agners** [comment]
> Tried the commands you gave - and I got this:

"This" did not make it to GitHub :sweat_smile:

**Comment by bearhntr** [comment]
Stefan,

After doing the  -- Beta command, I am seeing this now.  



Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by agners** [comment]
@bearhntr yeah I don't see anything here, you can't use email response for this it seems.

**Comment by bearhntr** [comment]
It shows there is an update:

Home Assistant Core Update
21 hours ago
2022.9.0b2


Home Assistant Core

Installed version
2022.8.7
Latest version
2022.9.0b2

================= Appears to be a BETA version.  


Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by agners** [comment]
Check `ha os info`, and use `ha os update` (not core).

**Comment by bearhntr** [comment]
Stefan,

You are amazing...  Saw there was an  RC1 update 9.0 today, and installed it.  

Tried enabling this:

```
sensor:
- platform: systemmonitor
resources:
- type: processor_temperature
```

but it still fails with this error:   

```
Logger: homeassistant.components.systemmonitor.sensor
Source: components/systemmonitor/sensor.py:350
Integration: systemmonitor (documentation, issues)
First occurred: 8:18:39 AM (1 occurrences)
Last logged: 8:18:39 AM
Cannot read CPU / processor temperature information
```

So I added the following:  

```
# Lines added for Command Line Testing (CPU Temp)
- platform: command_line
name: CPU Temperature
command: "cat /sys/class/hwmon/hwmon0/temp1_input"
# If errors occur, make sure configuration file is encoded as UTF-8
unit_of_measurement: "°C"
value_template: "{{ value | multiply(0.001) | round(1) }}"
```

and LOW & BEHOLD....  I have this:

sensor.cpu_temperature http://192.168.10.4:8123/developer-tools/state#
CPU Temperature
49.8 	unit_of_measurement: °C friendly_name: CPU Temperature


Thank You ... Thank You ... Thank You

Curtis Norris

---------------------------------------------
☝ Message is being sent via the web version of COMCAST e-mail,
please ignore any formatting issues you may encounter.

**Comment by agners** [comment]
Hm, weird that the systemmonitor does not pick it up. On my AMD system it seems to generate the following labels like `Tctl` and `CPU`, which are in the list of labels classified as CPU temperature (see https://github.com/home-assistant/core/blob/dev/homeassistant/components/systemmonitor/sensor.py#L291).

Would be interesting to see what your system produces exactly, from the OS shell:
```
docker exec -it homeassistant /bin/bash
python3
>>> import psutil
>>> psutil.sensors_temperatures()

```

**Comment by agners** [comment]
FYI, this should fix the temperature reading with `systemmonitor` integration: https://github.com/home-assistant/core/pull/78472

**Pull request merged**
