### PR TITLE
Update Raspberry Pi 3 device tree list

### PR DESCRIPTION
**Pull request by agners**
Make sure all Raspberry Pi devices using the BCM2837 SoC (or the SiP version RP3A0 of it) are deployed. This especially makes sure that we only deploy the downstream device trees (named bcm2710*) and deploy device trees for the CM3 as well as the Zero 2 and Zero 2 W consistently for 32-bit and 64-bit.

Fixes: #3298

### CODE REVIEW

**Review by sairon — CHANGES_REQUESTED** [review]
This needs rebase after RPi kernel bump to 6.6 :grimacing:

**Review by sairon — APPROVED** [review]
Looks good. Seems that the `broadcom/bcm2837-rpi-3-b` wasn't needed, it's the upstream DT with some downstream parts missing. Unless it was picked by FW in some cases (which IMHO doesn't make much sense) it should be safe to remove it.

**Comment by agners** [comment]
> Looks good. Seems that the `broadcom/bcm2837-rpi-3-b` wasn't needed, it's the upstream DT with some downstream parts missing. Unless it was picked by FW in some cases (which IMHO doesn't make much sense) it should be safe to remove it.

I've just checked on a Raspberry Pi 3 (non-plus), and it doesn't seem to get picked today (`/proc/device-tree/wifi-pwrseq` which is specific to the upstream device tree is not present).

**Comment by fabfix** [comment]
Hi @agners, thank you soo much for the fast resolution! 
Do you know in witch release this fix will available?

**Pull request merged**
