### PR TITLE
Add SocketCAN support

### PR DESCRIPTION
**Pull request by pergolafabio**
A Controller Area Network (CAN bus) is a robust vehicle bus standard designed to allow microcontrollers and devices to communicate with each other's applications without a host computer. It is a message-based protocol, designed originally for multiplex electrical wiring within automobiles to save on copper, but it can also be used in many other contexts. For each device, the data in a frame is transmitted sequentially but in such a way that if more than one device transmits at the same time, the highest priority device can continue while the others back off. Frames are received by all devices, including by the transmitting device.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @pergolafabio, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1228).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by agners** [comment]
Are there device drivers active to make use of CAN support? What kind of integration/add-on are you using?

**Comment by pergolafabio** [comment]
No addon/intergation excists yet for socketcan, we want first device suport so we can build one

Its all new to me, but normally socketcan drivers are already included in linuxkernel ?

https://en.wikipedia.org/wiki/SocketCAN
https://www.can-cia.org/fileadmin/resources/documents/proceedings/2012_kleine-budde.pdf
so i dont need to add those, right?

**Comment by pergolafabio** [comment]
ist used for adapters like these : https://canable.io/

canbus was support was recently included in latest ESPhome : https://esphome.io/components/canbus.html
but we want also native support with USB dongles

**Comment by agners** [comment]
Desktop distributions enable pretty much everything there is, but also with a size cost... We are a bit more picky. But that said, what make sense for Home Assistant should be enabled.

CAN is usually used in embedded industry, but not so much in Home Automation. That said, if there is a use case, I am fine adding it.

The modules you added are the core CAN modules, but for them to be useful you have to have some device driver enabled, that is why I am asking. In your case it seems that this is done using slcan and the `CONFIG_CAN_SLCAN` configuration.

**Comment by pergolafabio** [comment]
Yes, we have some use cases, a few, people on community forum are asking for it, for home automation purposes... We are now using esp8266 or Arduino hardware to control it, but native hardware integration would be a more proper solution


https://community.home-assistant.io/t/support-for-can-bus-peak-ixxat-canable-etc/249639

It's indeed using slcand, we can bring up the can0 interface up with some python commands

Kernel and driver's is quite new to me, so I am not 100% sure if the PR is enough? Do i need to add something else then?

**Comment by pergolafabio** [comment]
we are with multiple people interested in Canbus om community forum, we all have different hardware , for now those 3 are being used by other members to get this project started

**Comment by agners** [comment]
> Kernel and driver's is quite new to me, so I am not 100% sure if the PR is enough? Do i need to add something else then?

I don't think anything more is required. Socket CAN uses the socket interface, and the Home Assistant Core container runs with full access to the network interfaces, so you should be able to use Socket CAN out of the box.

**Comment by pergolafabio** [comment]
perfect, thnx @agners 
1 more question, i need to wait for the next "dev" version to test it out, right? https://os-builds.home-assistant.io/
once a new build is created, how can i upgrade my system to a dev build?  is it enought to join beta?

**Comment by pvizeli** [comment]
It's also possible to write an add-on with `kernel_module: true` and they can manage the kernel modules from OS to load it

**Comment by pergolafabio** [comment]
ok, thats interesting too, but its better to have an integration/component :-)

@pvizeli , can you tell me how i can update to an dev version to test ?

**Comment by pvizeli** [comment]
`ha su options --channel dev`

**Comment by pergolafabio** [comment]
> `ha su options --channel dev`

ok, if i run that command, i need to wait untill a next build is available here : https://os-builds.home-assistant.io/
then it should prompt me to update HassOS?

whats the difference then between the beta channel? is that the same command?

image

**Comment by pergolafabio** [comment]
ok, joined dev , but i dont receive an HassOS update prompt? while core and supervisor is prompting me for dev versions

is this normal behaviour? do i need a command to update to a specific HassOS version? i guess one of these here?
https://os-builds.home-assistant.io/
image

**Comment by pergolafabio** [comment]
@pvizeli @agners 

the command "slcand" is part of the apk package "can-utils"

Is this also possible as a request to add it in HassOS? This is just a questions... if not allowed , then we know that we need to build an add-on instead of a component/integration

thnx for feedback!

https://pkgs.alpinelinux.org/package/edge/community/x86/can-utils
https://github.com/linux-can/can-utils/blob/master/README.md
https://github.com/linux-can/can-utils/blob/master/README.md

**Comment by cybertza** [comment]
Hi Guys, any guide or alike to get this to work:

ip link set can0 up type can bitrate 500000
[ip link set can0 up type can bitrate 500000]
(ip: either "dev" is duplicate, or "type" is garbage)

Just want to pull it into node red attached to hass:

DEVLINKS: >-
  /dev/serial/by-id/usb-Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_2068389E4D4D-if00
  /dev/serial/by-path/pci-0000:00:15.0-usb-0:7:1.0
DEVNAME: /dev/ttyACM0
DEVPATH: /devices/pci0000:00/0000:00:15.0/usb1/1-7/1-7:1.0/tty/ttyACM0
ID_BUS: usb
ID_MODEL: CANable2_b158aa7_github.com_normaldotcom_canable2.git
ID_MODEL_ENC: CANable2\x20b158aa7\x20github.com\x2fnormaldotcom\x2fcanable2.git
ID_MODEL_ID: 117e
ID_PATH: pci-0000:00:15.0-usb-0:7:1.0
ID_PATH_TAG: pci-0000_00_15_0-usb-0_7_1_0
ID_REVISION: '0200'
ID_SERIAL: >-
  Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_2068389E4D4D
ID_SERIAL_SHORT: 2068389E4D4D
ID_TYPE: generic
ID_USB_DRIVER: cdc_acm
ID_USB_INTERFACES: ':020201:0a0000:'
ID_USB_INTERFACE_NUM: '00'
ID_USB_MODEL: CANable2_b158aa7_github.com_normaldotcom_canable2.git
ID_USB_MODEL_ENC: CANable2\x20b158aa7\x20github.com\x2fnormaldotcom\x2fcanable2.git
ID_USB_MODEL_ID: 117e
ID_USB_REVISION: '0200'
ID_USB_SERIAL: >-
  Openlight_Labs_CANable2_b158aa7_github.com_normaldotcom_canable2.git_2068389E4D4D
ID_USB_SERIAL_SHORT: 2068389E4D4D
ID_USB_TYPE: generic
ID_USB_VENDOR: Openlight_Labs
ID_USB_VENDOR_ENC: Openlight\x20Labs
ID_USB_VENDOR_ID: 16d0
ID_VENDOR: Openlight_Labs
ID_VENDOR_ENC: Openlight\x20Labs
ID_VENDOR_ID: 16d0
MAJOR: '166'
MINOR: '0'
SUBSYSTEM: tty
TAGS: ':systemd:'
USEC_INITIALIZED: '5433234'

**Comment by pergolafabio** [comment]
You may need to modprobe

**Comment by pergolafabio** [comment]
I do below


subprocess.call(['modprobe', 'can'])
subprocess.call(['modprobe', 'can_raw'])
subprocess.call(['modprobe', 'slcan'])

# for below you need to install cantools
os.system("slcand -o -c -s4 /dev/ttyACM0 can0")
os.system("ifconfig can0 txqueuelen 1000")
os.system("ifconfig can0 up")

**Comment by cybertza** [comment]
Thanks, can you slow it down for me a bit, I can do it from the ssh&web addon?

**Comment by cybertza** [comment]
#!/bin/bash
modprobe can
modprobe can_raw
modprobe slcan
slcand -o -c -s4 /dev/ttyACM0 can0
ifconfig can0 txqueuelen 1000
ifconfig can0 up


shell_command:
  setup_can: /config/setup_can.sh
  
  would this approach work?
  
  or would i have to create a addon, or mode the node addon?

**Comment by pergolafabio** [comment]
You can test indeed from ssh addon, but it's not persistent then, I have a canable, I flashed it with slcan ....

If you want to make it persistent, you can create an addon or run it in HA container with a custom component or script on launch HA

**Comment by cybertza** [comment]
https://github.com/dries007/HA_EnableCAN seems to have something in that line, i am a little stuck at the recommended commands there:

subprocess.call(['modprobe', 'can'])
subprocess.call(['modprobe', 'can_raw'])
subprocess.call(['modprobe', 'slcan'])


➜  ~ modprobe can
modprobe: can't change directory to '/lib/modules': No such file or directory

NameError: name 'subprocess' is not defined
>>> import subprocess
>>> subprocess.call(['modprobe', 'can'])
modprobe: can't change directory to '/lib/modules': No such file or directory

**Comment by pergolafabio** [comment]
I think you need to disable protected mode on the ssh addon, otherwhise it's not allowed

**Comment by pergolafabio** [comment]
The subprocess is for a python script, doesn't work on ssh addon offcourse, it easy just a dirty copy/paste

**Comment by cybertza** [comment]
Yea it is disabled, i Did run that in term and py

**Comment by cybertza** [comment]
Kindof where you are in this post now:

https://community.home-assistant.io/t/load-additional-kernel-module/217024/9

**Comment by pergolafabio** [comment]
I do it now with my example above in a custom component... But I have flashed SLCAN firmware on mine USB can

**Comment by cybertza** [comment]
Any idea where to get the slcan firmware?

**Comment by pergolafabio** [comment]
But It depends what you want Todo...

I have canable, I can update here:
https://canable.io/updater/

**Comment by cybertza** [comment]
I updated it to the same, I have the controller, like stated above it does mount to the usb, but if use mod probe the folder does not seem to exist on the hass install. 

Tried the docker approach but seems to have the same errors.

Is there some case config I need to do to the hass install or anything like that?

**Comment by pergolafabio** [comment]
Try doing the command inside the HA container itselff, try also the other SSH addon , i thought only 1 ssh addon allowed Todo it... With the ssh addon. Acces the HA container first...

Also try from the hassos itself, also try insmod command

**Pull request merged**
