### PR TITLE
updated generic-raw-uart and rpi-rf-mod package for kernel 6.1 compatibility

### PR DESCRIPTION
**Pull request by jens-maus**
This PR updates the generic-raw-uart and rpi-rf-mod package for kernel 6.1 compatibility. Especially the rpi-rf-mod package providing device overlays for the GPIO-based homematic RF modules had been updated to reflect recent changes for kernel 6.1 / latest generic-raw-uart compatibility.

### CODE REVIEW

**Review by pvizeli — APPROVED** [review]

**Comment by agners** [comment]
@jens-maus at this point we still use Linux 5.15 on dev for RPi's, is that compatible with both kernels?

**Comment by jens-maus** [comment]
Yes, should be compatible AFAIK.

**Comment by agners** [comment]
Do you happen to know if this addresses all build warnings, e.g. can we reeanble `-Werror`?

I think there have been build warnings before already, but the default in the kernel seems to have changed such that warnings are treated as errors by default, for the kernel itself and for out-of-tree modules. Because this modules seem to have build warnings, I added a fixup for the kernel config to disable `-Werror`, see https://github.com/home-assistant/operating-system/pull/2358/files#diff-72c01c163e47bd69d82dccf2423cd46c61e67900707e440ee6cc48307d021491.

**Comment by jens-maus** [comment]
> Do you happen to know if this addresses all build warnings, e.g. can we reeanble `-Werror`?

No, these build warnings are still there as you can see here:

```
  CC [M]  projekte/linux/RaspberryMatic/build-raspmatic_intelnuc/build/generic_raw_uart-b787f3d84b311bd3e07b0ca8f2aa63330030746e/kernel/hb_rf_eth.o
../generic_raw_uart-b787f3d84b311bd3e07b0ca8f2aa63330030746e/kernel/hb_rf_eth.c: In function ‘hb_rf_eth_init’:
../generic_raw_uart-b787f3d84b311bd3e07b0ca8f2aa63330030746e/kernel/hb_rf_eth.c:775:3: warning: ignoring return value of ‘sysfs_create_file’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  775 |   sysfs_create_file(&dev->kobj, &dev_attr_is_connected.attr);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../generic_raw_uart-b787f3d84b311bd3e07b0ca8f2aa63330030746e/kernel/hb_rf_eth.c:776:3: warning: ignoring return value of ‘sysfs_create_file’ declared with attribute ‘warn_unused_result’ [-Wunused-result]
  776 |   sysfs_create_file(&dev->kobj, &dev_attr_connect.attr);
      |   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  MODPOST projekte/linux/RaspberryMatic/build-raspmatic_intelnuc/build/generic_raw_uart-b787f3d84b311bd3e07b0ca8f2aa63330030746e/kernel/Module.symvers
```

While they are in principle non-critical I think only @alexreinert can address these warnings upstream so that we can later remove the `-Werror` workaround you added recently.

**Pull request merged**
