### PR TITLE
Drop Raspberry Pi 1/Zero W support

### PR DESCRIPTION
**Pull request by agners**
These boards support the rather ancient ARMv6 architecture only. We
officially stopped supporting them already two releases ago, its time to
say goodbye.

### CODE REVIEW

**Review by pvizeli — APPROVED** [review]

**Comment by tailg8nj** [comment]
What is the last release known to work on a pi zero w? :glances at brand new pi zero sitting on desk: Will you still support container / supervisor images just not OS?

**Comment by agners** [comment]
> What is the last release known to work on a pi zero w? :glances at brand new pi zero w sitting on desk: Will you still support [container / supervisor images](https://github.com/home-assistant/supervisor/pkgs/container/armhf-homeassistant-base) just not OS?

The OS release 6.6 still should work. Is it the Pi Zero W 1 or 2? 2 is not yet supported.

**Comment by myriznet** [comment]
How about Raspberry Pi Zero 2 W?

**Comment by agners** [comment]
> How about Raspberry Pi Zero 2 W?

There is a feature request open, along with a work around for now: https://community.home-assistant.io/t/support-raspberry-pi-zero-2-w/356814

**Pull request merged**
