### PR TITLE
RaspberryPi: Update kernel 6.1.63 - stable_20231123

### PR DESCRIPTION
**Pull request by sairon**

### CODE REVIEW

**Comment by sairon** [comment]
FF-merge [Buildroot PR](https://github.com/home-assistant/buildroot/pull/16) before merging this PR.

**Comment by jens-maus** [comment]
Please note: stable_20231123 bumps kernel to 6.1.63 and not 6.1.62

**Comment by sairon** [comment]
:facepalm: Thanks @jens-maus for spotting this.

**Comment by sairon** [comment]
Should be okay now. The kernel version is there only for documentation purposes but good catch anyway, thanks again!

**Review by agners — APPROVED** [review]

**Pull request merged**
