### PR TITLE
Add support for rtl8821cu WiFi Dongle

### PR DESCRIPTION
**Pull request by s-ol**
Using the module source code from https://github.com/brektrou/rtl8821CU, which appears to be what Hardkernel use for their own images.

The dongle needs to be put into working mode using:

    usb_modeswitch -KW -v 0bda -p 1a2b

I'm note sure where that would go right now, but it would be good to add that in an udev rule:

```
# SPDX-License-Identifier: GPL-2.0-or-later
# Copyright (C) 2018-present Team CoreELEC (https://coreelec.org)

# put wifi module from storage to wifi mode
SUBSYSTEM=="usb", ACTION=="add", ATTR{idVendor}=="0bda", ATTR{idProduct}=="1a2b", \
  RUN+="/bin/sh -c 'export usb_modeswitch=/storage/.kodi/addons/virtual.system-tools/bin/usb_modeswitch; [ -x ${usb_modeswitch} ] && ${usb_modeswitch} -KW -v ${ID_VENDOR_ID} -p ${ID_MODEL_ID} || echo usb_modeswitch: please install system-tools addon >/dev/kmsg'"
```

I've only enabled it for ODROID N2 right now since that's what I'm using, but if anyone lets me know what else to do I'm happy to change anything here.

See also this forum thread with more links: https://community.home-assistant.io/t/how-can-i-use-install-the-realtek-rtl8821cu-wifi-usb-dongle-on-home-assistant-os/416035/

ODROID WiFi module 5B uses the rtl8821cu chipset.

### CODE REVIEW

**Comment by homeassistant** [comment]
Hi @s-ol, 

It seems you haven't yet signed a CLA. Please do so [here](https://home-assistant.io/developers/cla_sign_start/?pr=home-assistant&#x2F;operating-system#1899).

Once you do that we will be able to review and accept this pull request.

Thanks!

**Comment by s-ol** [comment]
Hm, I just saw that there actually already is an udev ruleset at `/usr/lib/udev/rules.d/40-usb_modeswitch.rules` on my running instance that actually contains the right vendor/product ids:

```
# D-Link DWA-171 Wifi Dongle
ATTR{idVendor}=="0bda", ATTR{idProduct}=="1a2b", RUN+="usb_modeswitch '/%k'"
```

I don't know a lot about udev, but this looks exactly right, how come it isn't triggered?
I tried running `udevadm monitor` while plugging in the dongle and this is what I get:
```
KERNEL[1182.992695] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
KERNEL[1182.992999] change   /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
KERNEL[1182.993109] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0 (usb)
KERNEL[1182.993491] add      /devices/virtual/workqueue/scsi_tmf_0 (workqueue)
KERNEL[1182.993767] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0 (scsi)
KERNEL[1182.993851] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/scsi_host/host0 (scsi_host)
KERNEL[1182.993975] bind     /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0 (usb)
KERNEL[1182.994102] bind     /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
UDEV  [1182.997972] add      /devices/virtual/workqueue/scsi_tmf_0 (workqueue)
UDEV  [1183.015834] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
UDEV  [1183.035944] change   /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
UDEV  [1183.038000] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0 (usb)
UDEV  [1183.039417] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0 (scsi)
UDEV  [1183.041047] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/scsi_host/host0 (scsi_host)
UDEV  [1183.042299] bind     /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0 (usb)
UDEV  [1183.043676] bind     /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2 (usb)
KERNEL[1183.998688] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0 (scsi)
KERNEL[1183.998846] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0 (scsi)
KERNEL[1183.998991] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0 (scsi_device)
KERNEL[1183.999170] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0 (bsg)
UDEV  [1184.001067] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0 (scsi)
UDEV  [1184.002988] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0 (scsi)
UDEV  [1184.004950] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/scsi_device/0:0:0:0 (scsi_device)
UDEV  [1184.005245] add      /devices/platform/soc/ffe09000.usb/ff500000.usb/xhci-hcd.1.auto/usb1/1-1/1-1.2/1-1.2:1.0/host0/target0:0:0/0:0:0:0/bsg/0:0:0:0 (bsg)
```

**Comment by s-ol** [comment]
Okay, figured that out too: it seems that the `usb_modeswitch` buildroot package fails to install the required systemd unit file `usb_modeswitch@.service`; this because it [tests for presence of systemd at install time](https://github.com/Danw33/usb-modeswitch/blob/master/Makefile#L88):

	test -d $(SYSDIR) -a -e /usr/bin/systemctl && install --mode=644 usb_modeswitch@.service $(SYSDIR) || test 1

evidently this check fails and the file isn't installed. I guess this is an upstream bug though.

**Comment by s-ol** [comment]
The usb_modeswitch change is now in a PR at home-assistant/buildroot#2. With that PR merged and the submodule updated, the wifi dongle becomes plug and play :)

**Pull request merged**
